# Generated by Django 4.2.2 on 2023-09-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ('depart',), 'verbose_name': 'department', 'verbose_name_plural': 'departmentss'},
        ),
    ]
