# Generated by Django 4.2.2 on 2023-09-06 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolapp', '0002_alter_departments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ('depart',), 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AddField(
            model_name='departments',
            name='d_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
